signup
qraft-Inc/Qraft-Store-Innersource-FrontEnd pull request #4
Opened 2022-09-13 10:17 UTC by Atuheirebenadate

2022-09-16 16:17 UTC, amyyalex requested changes
I've left a few comments that should be addressed before this gets merged.

2022-09-16 16:17 UTC, amyyalex commented on src/App.js
> -function App() {
Why is line 4 to line 23 deleted?

2022-09-16 16:17 UTC, amyyalex commented on src/componets/Signup.js
> +                        {/* <label>
Why is line 44 to 48 commented out?
I suggest you delete the lines if they don't have any function

2022-09-16 16:17 UTC, amyyalex commented on src/componets/Signup.js
> +                    <p>____________________________ or Signup with _____________________________</p>
What is the essence of the undescore symbol used in line 56? 
If you were trying to acheive a space without line break, you should use &nbsp; instead
or if you trying to acheive the underscroe itself, you should use the html code for it which is &#95;

2022-09-16 16:17 UTC, amyyalex commented on src/css/signup.css
> + /* .all{
If the commented out lines dosen't serve any function, it's best removed so the code looks a bit tidy

2022-09-16 16:17 UTC, amyyalex commented on src/header.js
> +import React from 'react';
Move this file into the components folder

2022-09-21 06:42 UTC, HassanBahati commented
@amyyalex please review this PR and merge into develop

2022-09-21 15:49 UTC, amyyalex approved these changes

2022-09-24 10:57 UTC, HassanBahati commented
@Atuheirebenadate please ensure to pull from the upstream, your code references very old changes leading to enormous conflicts.

2022-09-24 10:57 UTC, closed without merging